### ISSUE TITLE
Roadmap to v7.0.0

### ISSUE THREAD

**Issue by i-like-robots** [i-like-robots/react-tag-autocomplete#6]
## Improvements and new features

- [x] Refactor to use a single shared state (enables richer interactions)
- [x] Refactor codebase from JS to TS (just for me but also avoids depending on external definitions)
- [x] Refactor to pass originally suggested tag to `onAdd` callback
- [x] Refactor resizable input to never render narrower than the placeholder text
- [x] Add label sub-component (improves accessibility)
- [x] Add assistive text notifications for additions and deletions (improves accessibility)
- [x] Add support for disabled state (new feature)
- [x] Add support for invalid state and error messages (new feature, improves accessibility)
- [x] Add support for all expected combobox keyboard behaviours (improves usability and accessibility)
- [x] Add support for displaying the selected state for options in listbox (improves usability and accessibility)
- [x] Add support for fully customisable/translatable text
- [x] Add support for custimisable class names on every component 
- [x] Add new public API for input and listbox control
- [x] Improve support for overriding built in components/passing custom render props

## Other breaking changes

- [x] Upgrade to React v18 (chore)
- [x] Rename `onAddition` prop to `onAdd` (consistency)
- [x] Rename `tags` prop to `selected` (consistency and clarity)
- [x] Rename `removeButtonText` to `deleteButtonText` (consistency)
- [x] Rename `autoresize` prop to `allowResize` (consistency)
- [x] Remove `suggestionsFilter` prop (not needed, use `suggestionsTransform`)
- [x] Remove `maxSuggestionsLength` prop (not needed, use `suggestionsTransform`)

Please see [the changelog](https://github.com/i-like-robots/react-tag-autocomplete/blob/main/changelog.md) and [migration guide](https://github.com/i-like-robots/react-tag-autocomplete/blob/main/migration-guide.md) for more details.

**Comment by i-like-robots** [comment]
@saatviknagpal This behaviour should now be achieved by providing a  custom `suggestionsTransform`

**Comment by Tomas2D** [comment]
Hello, any progress on the point `Improve support for overriding built in components/passing custom components`. It would really fit my needs. Thanks!

**Comment by i-like-robots** [comment]
@Tomas2D I've released v7.0.0-beta.7 which exposes the render props, more details are here: https://github.com/i-like-robots/react-tag-autocomplete/issues/8#issuecomment-1256506007

**Comment by Tomas2D** [comment]
Perfect, thanks a lot!

**Comment by v-ageenko-rudesktop** [comment]
Hey @i-like-robots, if there is a chance for a soon update, I would like to ask you add ability to disable yellow \<mark\>-ing in text. It's not always reasonable to show matching like this. I'm using `react-tag-autocomplete@7.0.0-rc.6` and there is no such option 

Screenshots:
![изображение](https://user-images.githubusercontent.com/127081158/236130012-3194edf8-31a9-4f84-9096-a3af82289081.png)
![изображение](https://user-images.githubusercontent.com/127081158/236130163-a20030a7-baaf-40b8-a7af-ca31d841ccd5.png)


Thanks a lot! 
Vladimir, RuDesktop Co.

**Comment by i-like-robots** [comment]
@v-ageenko-rudesktop this is a good point - and I'm not sure using `<mark>` is actually the best solution because differest assistive tech will announce the contents separately to the parent word.

**Comment by i-like-robots** [comment]
@v-ageenko-rudesktop [r.c.7](https://github.com/i-like-robots/react-tag-autocomplete/releases/tag/v7.0.0-rc.7) now has support for a [`renderHighlight`](https://github.com/i-like-robots/react-tag-autocomplete#renderHighlight-optional) prop to customise the option text highlighting.

**Comment by v-ageenko-rudesktop** [comment]
@i-like-robots THANKS!
